name: Tensorboard on CML
description: How to run Tensorboard on CML
author: Cloudera Inc.
specification_version: 1.0
prototype_version: 1.0
date: "2021-07-06"

runtimes:
  - editor: Workbench
    kernel: Python 3.6
    edition: Standard

tasks:
  - type: run_session
    name: Install Dependencies
    script: cml/install_dependencies.py
    memory: 4
    cpu: 2

  - type: start_application
    name: Launch Tensorboard
    subdomain: tensorboard
    script: cml/launch_tensorboard.py
    memory: 1
    cpu: 1

  - type: run_session
    name: Train Model
    script: load_and_train.py
    memory: 4
    cpu: 2
